<!DOCTYPE html>
<html lang="en" xml:lang="en" xmlns="http://www.w3.org/1999/xhtml">
  <head>
    <title>about us - tecgaze web development , mobile apps and software </title>
    <link rel="icon" type="image/png" href="image/tecgaze-main.gif">
    <meta charset="utf-8">
    <meta name="description" content="tecgaze is for websites , software , app development, database & social media management, civil design , graphics design, content writing, seo">
    <meta name="keywords" content="website, seo, software, database, graphics,content, social media, mechanical, civil, php, javascript, sri lanka, online business">
    <meta name="author" content="Anuradha Pathirana">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="content-language" content="en-us">

    <meta property="og:title" content="home - tecgaze web development , mobile apps and software ">
<meta property="og:site_name" content="tecgaze">
<meta property="og:url" content="http://www.tecgaze.com/">
<meta property="og:description" content="tecgaze is a multi service company. services we offering are web designing & developing / software developing / mobile apps / deep learning / machine learning / database management / SEO.">
<meta property="og:type" content="website">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-main.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-app.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-autocad.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-deep-learning.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-graphics.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-seo-script-article-writing.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-social-media.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-software.gif">
<meta property="og:image" content="http://www.tecgaze.com/image/tecgaze-web-develop-and-design.gif">

<!-- Global site tag (gtag.js) - Google Analytics -->
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-169245022-1"></script>
<script>
  window.dataLayer = window.dataLayer || [];
  function gtag(){dataLayer.push(arguments);}
  gtag('js', new Date());

  gtag('config', 'UA-169245022-1');
</script>

    <!-- Bootstrap core CSS -->
      <link href="css/bootstrap.min.css" rel="stylesheet">
      <!-- Bootstrap core JS -->
      <script src="js/bootstrap.min.js" type="text/javascript"></script>
      <!-- Fonts -->
      <link href="css/font.css" rel="stylesheet">
      <!-- custom css -->
      <link href="css/pagecss.css" rel="stylesheet">
      <style type="text/css">
        input[type=text], select, [type=date], [type=password] {
          width: 100%;
          padding: 4px 10px;
          margin: 1px 0;
          display: inline-block;
          border: 1px solid #ccc;
          border-radius: 10px;
          box-sizing: border-box;
          }
      </style>
      <script src="js/functions.js" type="text/javascript"></script>
      <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
      <!-- JSON-LD markup generated by Google Structured Data Markup Helper. -->
      <script type="application/ld+json">
      {
        "@context" : "http://schema.org",
        "@type" : "LocalBusiness",
        "name" : "tec-gaze",
        "image" : "image/tecgaze-main.gif",
        "telephone" : "+9471514218",
        "email" : "tecgazeinfo@gmail.com",
        "address" : {
          "@type" : "PostalAddress",
          "streetAddress" : "Temple road",
          "addressLocality" : "Mainnoluwa",
          "addressRegion" : "Warakapola",
          "addressCountry" : "Sri Lanka"
        },
        "openingHoursSpecification" : {
          "@type" : "OpeningHoursSpecification",
          "dayOfWeek" : {
            "@type" : "DayOfWeek",
            "name" : "Sunday - Saturday"
          },
          "opens" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30",
          "closes" : "Please insert valid ISO 8601 date/time here. Examples: 2015-07-27 or 2015-07-27T15:30"
        }
      }
      </script>
  </head>
  <body class="container-fluid text-center" style="justify-content: center;">
    <div class="row hgs4l text-center" style="width: 100%;background-color:black;margin-left: 0;margin-right: 0;color: white;">
      <div class="col-sm-4 col-xs-12 text-left hidden-xs">
        <h4><a href="index.php" style="text-decoration: none;color: white;font-size: 25px;"> tecgaze </a></h4>
      </div>
      <div class="col-sm-4 col-xs-12 text-center visible-xs">
        <h3><a href="index.php" style="text-decoration: none;color: white;font-size: 25px;"> tecgaze </a></h3>
      </div>
      <div class="col-sm-8 col-xs-12 text-right hidden-xs">
        <p style="font-size: 20px;padding-top: 1%;"><span><a style="color: white;" href="aboutus.php"> about us </a></span><span> | <a style="color: white;" href="contactus.php"> contact us </a> <span>| portfolio</span></p>
      </div>
      <div class="col-sm-8 col-xs-12 text-center visible-xs">
        <p style="font-size: 20px;padding-top: 1%;"><span><a style="color: white;" href="aboutus.php"> about us </a></span><span> | <a style="color: white;" href="contactus.php"> contact us </a> <span>| portfolio</span></p>
      </div>
      <div class="col-sm-8 col-xs-12 text-center visible-xs">
        
      </div>
    </div>
    <div class="row hgs4l text-right" style="width: 100%;background-color:black;margin-left: 0;margin-right: 0;color: white;">
      <div class="col-xs-12 text-right">
        <p>tecgazeinfo@gmail.com / 0715194218</p>
      </div>
    </div>
    <div class="row hgs4l" style="width: 100%;padding-top: 20px;padding-bottom: 50px;">
      <div class="col-xs-12 text-center">
        <h2>About Us</h2>
      </div>
      <div class="col-xs-12 text-center">
        <img alt="tecgaze web developent , design , seo, graphic design company aboutus" src="image/tecgaze-aboutus.gif" style="width: 100%;margin-right: 0;margin-left: 0;">
      </div>
      <div class="col-xs-12 text-center">
        <p> Tecgaze is a multi service company. services we offering are web designing & developing / software developing / mobile apps / deep learning / machine learning / database management / SEO / ardino / script writing /article writing / type writing / house planing / 2D & 3D design / Logos / Graphic Design. We are full-stack web developers with three-year experience in web programming and the ability to code efficiently using PHP,Javascript and Java. I have successfully completed a number of web development projects. We acquired hands on app development using android studio. We also have experience in graphic designing (Adobe photoshop, Adobe illustrator). Furthermore, We possess good experience in computer hardware and microcontroller systems.
        We have proven excellent performances working in fast paced and challenging environments by been able to understand technical issues and offer solutions. Based on our web development knowledge and experiences as per your requirements; We strongly believe We could be an asset for your esteemed organization. We have the ability to manage a team in order to complete a web project and We try my best to complete web projects on time with an efficiency of 100%. </p>
      </div>
    </div>
    <div class="row footer text-center" style="bottom: 0;width: 100%;position: fixed;">
      <p style="background-color: black;color: white">2020 Copyright: www.tecgaze.com</p>
    </div>
  </body>
</html>